name: Comment-test-model
on:
  issue_comment:
    types: 
      - created
jobs:
  cmt-prepare:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/test-model')
    outputs:
      command: ${{ steps.split-comment-body.outputs._0 }}
      target-model: ${{ steps.split-comment-body.outputs._1 }}
    steps:
      - name: Split comment body
        uses: jungwinter/split@v2
        id: split-comment-body
        with:
          msg: '${{ github.event.comment.body }}'
      # - name: Check command
      #   if: steps.split-comment-body.outputs._0 != '/test-model'
      #   run: exit 1
      - name: Edit comment with error message
        if: failure()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > Command error ${{ steps.split-comment-body.outputs._0 }}
      - name: Prepared
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
          echo "- target command: ${{ steps.split-comment-body.outputs._0 }}"
          echo "- args: ${{ steps.split-comment-body.outputs._1 }}"
  trainModel:
    needs: cmt-prepare
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    defaults:
      run:
        working-directory: ./models/${{needs.cmt-prepare.outputs.target-model}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          fetch-depth: 0
      # may need to setup NodeJS & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      - uses: iterative/setup-cml@v1
      - name: Check working directory
        run: |
          pwd
          echo "./models/${{needs.prepare.outputs.target-model}}"
      - name: Pip requirement
        run: |
          pip uninstall protobuf python3-protobuf
          pip install --upgrade pip
          pip install --upgrade protobuf

          pip install -r requirements.txt
      - name: Train model
        run: |
          python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACC_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SEC_ID }}
        run: |
          python evaluate.py

          echo "## Model Metrics" >> report.md
          dvc metrics diff HEAD --show-md >> report.md

          echo "## Data" >> report.md
          cml-publish cnf_matrix.png --md >> report.md
          
          echo "github: ${{ github }}"
          echo "sha: ${{ github.event.pull_request.head.sha || github.sha }}"
          cml-send-comment --commit-sha=${{ github.event.pull_request.head.sha || github.sha }} report.md
  output:
    needs: trainModel
    runs-on: ubuntu-latest
    steps:
      - name: Create URL to the run output
        id: vars
        run: |
          echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          echo ::set-output name=report-url::https://github.com/$GITHUB_REPOSITORY/commit/${{ github.event.pull_request.head.sha || github.sha }}
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            [Model report output][1]
            [Github action run output][2]

            [1]: ${{ steps.vars.outputs.report-url }}
            [2]: ${{ steps.vars.outputs.run-url }}
